import { lesson, part, word } from './content-helpers.js';

export const foodChapter = {
  id: 'food',
  title: 'Food',
  fullTitle: 'Food: our basic need',
  icon: 'food',
  colour: 'peach',
  intro: 'Build a balanced meal, untangle nutrient words, and learn safe food and healthy-habit ideas.',
  summary: [
    'Food supplies nutrients for energy, growth, repair, and normal body functions. Foods come from plants and animals. Most foods contain a mixture of nutrients, so one food does not have just one job.',
    'Carbohydrates in foods such as rice and potatoes are useful energy sources. Proteins in pulses, beans, milk, or eggs support growth and repair. Fats also supply energy and help the body; we need a suitable balance, not a rule that all fat is bad.',
    'Vitamins and minerals are needed in small amounts for many body functions. Vitamin A supports normal vision and skin, and vitamin C supports healthy tissues and immune functions. Calcium helps bones and teeth; iron supports normal blood formation. These nutrients do not guarantee that nobody becomes ill.',
    'Dietary fibre, or roughage, from plant foods is not digested like starch in the small intestine. It supports normal bowel movements. Water is needed throughout the body and is also present in many foods. The exact fraction of water in a body varies.',
    'A balanced diet provides a variety of nutrients, suitable amounts, fibre, and safe water. Needs vary with growth and activity. A growing child needs enough protein, but not automatically more total protein than every adult. Ask an adult about individual food needs or allergies.',
    'Food preservation helps slow spoilage. Methods include drying, pickling, refrigeration, deep freezing, and controlled canning or bottling. Cold storage does not kill all germs, and a closed jar alone is not safe preservation. Adults handle food preparation and preservation; never taste suspicious food to check it.',
    'Food works alongside rest, comfortable posture, and regular suitable activity. School-age children usually need about 9–12 hours of sleep in a day. Play or supervised yoga can be useful. For pain, unusual tiredness, or health worries, tell a trusted adult rather than asking Buddy to diagnose.',
  ],
  checklist: [
    'Match carbohydrates, proteins, fats, vitamins, and minerals to their main roles.',
    'Give plant and animal food examples and remember that foods contain mixtures.',
    'Distinguish dietary fibre from clothing fibre, and explain why water matters.',
    'Explain a balanced diet without giving everyone the same meal or amount.',
    'Compare drying, pickling, cooling, freezing, and safe sealing as preservation ideas.',
    'Remember that preservation does not reverse spoilage or prove food is germ-free.',
    'Describe rest, posture, activity, and yoga safely.',
    'Use grams/kilograms for mass and litres/kilolitres for volume.',
  ],
  examples: [
    { title: 'A varied lunch', text: 'Roti or rice, dal, vegetables, and safe water contribute different nutrients. Families can choose suitable alternatives.' },
    { title: 'One food, several roles', text: 'Pulses supply protein but also contain other nutrients. Nuts contain fat and protein, not just one of them.' },
    { title: 'A food label', text: 'A rice pack may show mass in kilograms; a milk carton may show volume in litres. Liquids also have mass.' },
  ],
  diagram: {
    title: 'Different roles in a varied meal',
    steps: ['Carbohydrates/fats: energy', 'Protein: growth and repair', 'Vitamins/minerals: body functions', 'Fibre and water: normal digestion'],
    note: 'These are helpful role labels, not an order of eating or four separate, exclusive kinds of food.',
  },
  extraDiagrams: [{
    title: 'Food ideas meet the next guide',
    steps: ['Food supplies nutrients', 'Digestion breaks food down', 'Useful substances are absorbed', 'The body uses them'],
    note: 'Digestion & microbes is guide 02. This is a connection between ideas, not the full organ-by-organ food route.',
  }],
  memory: 'Variety, suitable amounts, fibre, safe water, and healthy routines work together.',
  starters: ['food-needs', 'food-balanced', 'food-preservation'],
  mcqs: [
    { id: 'food-q1', question: 'Why is a meal with rice, dal, and vegetables more varied than rice alone?', options: ['Every food supplies exactly the same thing', 'The foods contribute different nutrients and fibre', 'Vegetables remove all nutrients from rice', 'Only the colour matters'], correct: 1, explanation: 'A varied meal can provide different nutrients and fibre. Each food can contain several nutrients; the groups are not exclusive boxes.' },
    { id: 'food-q2', question: 'Which nutrient has a main role in growth and repair?', options: ['Only water vapour', 'Only cloth fibre', 'Protein', 'A preservative jar lid'], correct: 2, explanation: 'Protein supports growth and repair. Pulses, beans, milk, and eggs are examples of protein-containing foods; suitable choices differ between families.' },
    { id: 'food-q3', question: 'What does dietary fibre mainly help with in this revision guide?', options: ['Normal bowel movements', 'Making a sweater', 'Turning all food into fat', 'Replacing all drinking water'], correct: 0, explanation: 'Dietary fibre, or roughage, supports normal bowel movements. Clothing fibre is a different meaning, and fibre does not replace water.' },
    { id: 'food-q4', question: 'Which statement about cold food storage is most careful?', options: ['Freezing makes any spoiled food fresh again', 'A fridge kills every germ', 'Every chilled food is safe forever', 'Cooling can slow spoilage, but storage still needs adult care'], correct: 3, explanation: 'Cooling slows many processes that spoil food, but does not kill every germ or reverse spoilage. Adults should check labels and safe storage.' },
    { id: 'food-q5', question: 'A package shows “1 litre” of milk. What is being measured?', options: ['The cow’s age', 'The milk’s volume', 'Only its protein amount', 'The number of germs'], correct: 1, explanation: 'Litres measure volume. Grams and kilograms measure mass. Milk has both mass and volume, even when its label uses litres.' },
    { id: 'food-q6', question: 'Which routine supports health alongside a balanced diet?', options: ['Staying up late every night', 'Ignoring pain during exercise', 'Regular rest, comfortable posture, and suitable activity', 'Taking vitamins without an adult'], correct: 2, explanation: 'Rest and suitable activity support health. Ask adults about routines and health worries; supplements and strenuous activities are not things to choose alone.' },
  ],
  shortAnswers: [
    { id: 'food-s1', question: 'Explain the main roles of carbohydrates, proteins, fats, vitamins, and minerals.', answer: 'Carbohydrates and fats provide energy. Protein supports growth and repair. Vitamins and minerals support many normal body functions. Calcium helps bones and teeth and iron supports blood formation. Most foods contain a mixture, not just one nutrient.' },
    { id: 'food-s2', question: 'Describe a balanced diet and the jobs of fibre and water.', answer: 'A balanced diet gives a variety of nutrients in suitable amounts, plus dietary fibre and safe water. Fibre supports normal bowel movements, and water is needed for body functions. Needs vary with age and activity, so adults help choose suitable meals.' },
    { id: 'food-s3', question: 'Name five preservation methods and explain an important safety limit.', answer: 'Drying, pickling, refrigeration, deep freezing, and controlled canning or bottling can help preserve food. Drying reduces water; cooling slows spoilage; safe sealing needs a proper process. These methods do not make any spoiled food fresh again. Adults must handle the methods and suspicious food should not be tasted.' },
    { id: 'food-s4', question: 'Explain rest, posture, and exercise, and distinguish mass from volume on food labels.', answer: 'Rest gives the body a break; sleep is an important form of rest. Posture is body position, and suitable activity or supervised yoga can support health. Grams and kilograms measure mass, while litres and kilolitres measure volume. Food, rest, and activity all matter.' },
  ],
};

function w(id, term, definition, example, simple, aliases = [], parts = []) {
  return { ...word(id, 'food', term, definition, example, aliases, parts), simple };
}

export const foodGlossary = [
  w('food-sources', 'Food sources', 'The plants or animals from which food is obtained. A prepared dish may combine several sources.', 'Wheat and beans are plant sources; cow’s milk and eggs are animal sources.', 'Foods can come from plants, animals, or a mixture.', ['plant food', 'animal food', 'foodstuffs']),
  w('food-carbohydrates', 'Carbohydrates', 'Nutrients including sugars and starch that are important energy sources. Many foods contain them along with other nutrients.', 'Rice, roti, potatoes, and corn contain carbohydrates.', 'Carbohydrates are useful energy nutrients.', ['carbohydrate', 'carbs'], [
    part('Sugar', 'A type of carbohydrate; sugars occur naturally in some foods and can also be added.', ['sugars']),
    part('Energy-giving foods', 'A school grouping for foods rich in carbohydrates or fats; these provide energy.', ['energy giving food']),
  ]),
  w('food-protein', 'Protein', 'A nutrient used for growth, repair, and many other body jobs. Growing bodies need adequate protein, not one identical amount for everyone.', 'Pulses, beans, milk, and eggs can provide protein.', 'Protein helps growth and repair.', ['proteins'], [
    part('Body-building foods', 'A school label for protein-rich foods that support growth and repair.', ['body building food']),
  ]),
  w('food-fats', 'Dietary fats', 'Nutrients that provide concentrated energy and support body functions. Some fat is needed; a suitable balance matters.', 'Nuts, oil, ghee, and butter contain fats and can have other nutrients too.', 'We need some fat as part of a balanced diet.', ['fat', 'fats', 'dietary fat']),
  w('food-vitamins', 'Vitamins', 'Nutrients needed in small amounts for normal body processes. They do not supply energy like carbohydrates or guarantee that illness never occurs.', 'Different foods provide different vitamins, so variety matters.', 'Vitamins help body processes work normally.', ['vitamin', 'protective food', 'protective foods'], [
    part('Vitamin A', 'A vitamin supporting normal vision and healthy skin.'),
    part('Vitamin B-complex', 'A group of vitamins supporting several body functions, including using food normally.', ['vitamin b complex', 'vitamin b']),
    part('Vitamin C', 'A vitamin supporting healthy tissues, gums, and normal immune functions.'),
    part('Vitamin D', 'A vitamin helping the body use calcium for healthy bones.'),
    part('Vitamin E', 'A vitamin supporting healthy cells.'),
    part('Vitamin K', 'A vitamin supporting normal blood clotting; it is not medicine to take alone.'),
  ]),
  w('food-minerals', 'Minerals in food', 'Nutrients such as calcium and iron that the body needs in suitable amounts. This is a nutrition meaning, not just rock or soil particles.', 'Milk and curd can supply calcium; beans and leafy vegetables can contribute iron.', 'Mineral nutrients support important body jobs.', ['food minerals', 'nutrition minerals'], [
    part('Calcium', 'A mineral nutrient supporting bones and teeth.'),
    part('Iron', 'A mineral nutrient involved in normal blood formation.'),
    part('Potassium', 'A mineral nutrient involved in normal nerve and muscle functions.'),
    part('Iodine in food', 'A mineral nutrient needed in small amounts. This is not an instruction to use iodine solutions or supplements.', ['dietary iodine']),
    part('Sodium', 'A mineral nutrient involved in fluid balance and other functions; needing it does not mean adding lots of salt.'),
  ]),
  w('dietary-fibre', 'Roughage (dietary fibre)', 'Parts of plant food not digested like starch in the small intestine. Fibre supports normal bowel movements and is different from clothing fibre.', 'Whole grains, fruit, and vegetables contribute dietary fibre.', 'Roughage helps normal bowel movements.', ['roughage', 'dietary fibre', 'dietary fiber', 'food fibre', 'fiber in food', 'fibre in food']),
  w('diet-water', 'Water in our diet', 'Water is needed for normal body functions and comes from safe drinks and many foods. Body-water percentage varies between people.', 'Fruit and other foods contain water as well as nutrients.', 'The body needs safe water; food can contain water too.', ['dietary water', 'water in food']),
  w('diet-balanced', 'Balanced diet', 'A varied pattern of food supplying suitable nutrients, fibre, and safe water for a person’s needs.', 'Roti or rice, dal, vegetables, and water make a more varied meal than one food alone.', 'A balanced diet combines variety and suitable amounts.'),
  w('food-diet', 'Diet & meal', 'A diet is the usual pattern of food and drink. A meal is food eaten at one occasion. Diet does not mean only eating to change weight.', 'One lunch is a meal; a person’s usual food pattern is their diet.', 'Diet is the pattern; a meal is one occasion.', [], [
    part('Diet', 'The usual pattern of foods and drinks.'),
    part('Meal', 'Food eaten together at one occasion.', ['meals']),
  ]),
  w('preservation-spoilage', 'Preservation & spoilage', 'Food preservation helps slow unwanted changes and spoilage. Spoilage means food has changed in ways that can make it unsuitable to eat.', 'Do not taste suspicious food to decide whether it is safe.', 'Preservation slows spoilage; it does not reverse it.', [], [
    part('Food preservation', 'Keeping food suitable for longer using controlled storage or treatment.'),
    part('Spoilage', 'Unwanted changes that can make food unsuitable to eat.', ['spoilt food', 'spoiled food']),
  ]),
  w('food-drying', 'Drying food', 'Reducing food’s water content to help slow spoilage. Drying is not a promise that every germ is killed.', 'Raisins are dried grapes.', 'Drying reduces water in food.', ['drying', 'dried food']),
  w('food-pickling', 'Pickling', 'Preserving some foods using suitable salt or acidic conditions and a controlled recipe. Oil or salt alone does not automatically make food safe.', 'Pickled mango is an example; adults handle preparation.', 'Pickling uses carefully chosen preserving conditions.', ['pickle', 'pickles']),
  w('chill-freeze', 'Refrigeration & deep freezing', 'Refrigeration keeps food cool; deep freezing keeps it much colder and frozen. Both can slow spoilage, but do not kill all germs.', 'Follow food labels and ask adults about safe storage.', 'Cool or frozen storage slows spoilage; it does not fix spoiled food.', ['refrigerating', 'deep freeze', 'refrigerator', 'fridge'], [
    part('Refrigeration', 'Keeping food cool to slow spoilage, with appropriate adult-managed storage.', ['refrigerating']),
    part('Deep freezing', 'Keeping food frozen at a much lower temperature to slow spoilage for suitable foods.', ['deep freeze']),
  ]),
  w('can-bottle', 'Canning & bottling', 'Preserving suitable foods using controlled treatment and sealing in containers. Closing any jar or bottle by itself is not safe preservation.', 'An adult may buy properly processed bottled sauce or canned food.', 'Safe canning and bottling need a proper process, not just a lid.', [], [
    part('Canning', 'Controlled processing and sealing of food in cans or other suitable containers.'),
    part('Bottling', 'Controlled processing and storage in suitable sealed bottles or jars.'),
  ]),
  w('legumes-pulses', 'Legumes & pulses', 'Legumes are plants such as beans and peas that produce seeds in pods. Pulses are the dry edible seeds of some legumes.', 'Lentils and many dry beans are pulses; not every legume is called a pulse.', 'Legumes are a plant group; pulses are some of their edible dry seeds.', [], [
    part('Legume', 'A plant in the bean-and-pea family, usually producing seeds in pods.', ['legumes']),
    part('Pulse', 'A dry edible seed of some legumes, such as a lentil.', ['pulses', 'lentils', 'dal']),
  ]),
  w('food-cereals', 'Cereals', 'Food grains from grasses, including rice, wheat, and corn. A cereal-based product may contain additional ingredients.', 'A sweetened breakfast product is not nutritionally identical to plain grain.', 'Rice, wheat, and corn are cereal grains.', ['cereal', 'grain', 'grains']),
  w('rest-posture', 'Rest, sleep & posture', 'Rest gives the body a break; sleep is an important form of rest. Posture is the position of the body when sitting, standing, or moving.', 'Use a comfortable supported sitting position and tell an adult about pain.', 'Rest gives a break. Sleep is rest. Posture is body position.', [], [
    part('Rest', 'Time or activity that gives the body a break.'),
    part('Sleep', 'An important resting state; school-aged children need a regular, adequate sleep routine.'),
    part('Posture', 'The position of the body while sitting, standing, or moving.'),
  ]),
  w('exercise-yoga', 'Exercise & yoga', 'Suitable physical activity helps the body stay active and healthy. Yoga combines practices such as postures and breathing, with safe adult guidance.', 'International Yoga Day is on 21 June; care for health is not limited to a celebration day.', 'Suitable movement and supervised yoga can support health.', ['International Yoga Day'], [
    part('Exercise', 'Physical activity suited to the person that supports health.'),
    part('Yoga', 'A tradition of practices including movement, postures, and breathing; children need suitable adult guidance.'),
  ]),
  w('food-units', 'Food measurements: mass & volume', 'Grams and kilograms measure mass; litres and kilolitres measure volume. A liquid also has mass, even when its label shows litres.', 'A rice bag may list kilograms, while a milk carton lists litres.', 'Mass uses g/kg. Volume uses L/kL.', ['food measurements'], [
    part('Gram', 'A unit of mass; one kilogram is 1000 grams.', ['grams', 'g']),
    part('Kilogram', 'A unit of mass equal to 1000 grams.', ['kilograms', 'kg']),
    part('Litre', 'A unit of volume; one kilolitre is 1000 litres.', ['liter', 'litres', 'liters', 'l']),
    part('Kilolitre', 'A unit of volume equal to 1000 litres.', ['kiloliter', 'kilolitres', 'kiloliters', 'kl']),
  ]),
];

export const foodKnowledge = [
  lesson('food-needs', 'food', 'Why do we need food?',
    ['Why do we need food?', 'What are nutrients?', 'Where do foods come from?', 'Are plant based drinks the same as animal milk?'],
    ['food', 'nutrients', 'plant food', 'animal food', 'milk'],
    'Food supplies nutrients for energy, growth, repair, and normal body functions. Food sources can be plants or animals, and many dishes combine them. Cow’s milk is an animal food; soy or almond drinks come from plants. Similar names do not mean identical nutrients.',
    'Food gives the body useful nutrients. Different foods contribute different things.',
    'Most foods contain a mixture of nutrients. Not every nutrient supplies energy in the same way: vitamins support body processes rather than serving as energy-rich fuel. Families choose foods suited to their needs.',
    'Wheat, beans, and fruit are plant foods; eggs and cow’s milk are animal foods.',
    'energy grow growth repair functions source sources plants animals mixtures body healthy drinks soy almond nutrients'),
  lesson('food-groups', 'food', 'How do the food-group roles differ?',
    ['How do energy giving body building and protective foods differ?', 'What are the main nutrient groups in this guide?', 'Can one food contain several nutrients?', 'Are vitamins an energy rich fuel?'],
    ['food group', 'nutrients', 'carbohydrate', 'protein', 'fat', 'vitamin', 'mineral'],
    'For this revision, carbohydrates and fats are energy-giving nutrients; protein supports growth and repair; vitamins and minerals support body processes. Fibre and water also matter. These are helpful role labels, not exclusive boxes: most foods contain several nutrients.',
    'Energy, growth and repair, and normal body functions are different roles. One food can help in several ways.',
    'Rice and potatoes contain carbohydrates. Pulses provide protein and other nutrients. Nuts contain fat and protein. Vitamins do not supply energy like carbohydrate or fat, and no food guarantees freedom from every illness.',
    'Dal contains protein but also other nutrients, so “body-building food” is not its only role.',
    'groups roles role energy giving body building protective carbohydrates proteins fats vitamins minerals fibre water mixed mixtures several'),
  lesson('food-proteins-fats', 'food', 'Carbohydrates, protein, or fat?',
    ['How do carbohydrates proteins and fats differ?', 'Why do growing bodies need protein?', 'Does every child need more total protein than every adult?', 'Is all dietary fat bad?'],
    ['carbohydrate', 'protein', 'fat', 'growing', 'child'],
    'Carbohydrates are useful energy sources. Protein supports growth and repair. Fat provides concentrated energy and has important body roles too. Growing children need adequate protein, but needs vary: a child does not automatically need more total protein than every adult. A suitable balance matters, not banning all fat.',
    'Carbohydrates help supply energy, protein supports growth, and some fat is needed too.',
    'Food needs vary with age, growth, activity, and other factors. This guide cannot prescribe individual amounts or weight-change plans. Ask a trusted adult or qualified professional about personal needs.',
    'Roti contributes carbohydrate, dal contributes protein, and nuts contain fats as well as protein.',
    'energy concentrated growth repair children adults total amount amounts need needs bad balance roti dal nuts'),
  lesson('food-vitamins-minerals', 'food', 'What do vitamins and minerals help with?',
    ['How do vitamins and minerals help the body?', 'Which nutrients support bones teeth and blood formation?', 'Does vitamin C guarantee no infections?', 'What is iodine in food?'],
    ['vitamin', 'mineral', 'calcium', 'iron', 'iodine in food'],
    'Vitamins and minerals support normal body processes. Vitamin A supports normal vision and skin; vitamin C supports tissues and immune functions but does not guarantee no infection. Calcium supports bones and teeth, and iron supports normal blood formation. Iodine is a mineral nutrient needed in small amounts, not an instruction to use iodine liquids or supplements.',
    'Vitamins and minerals help the body work normally. Calcium helps bones; iron helps blood.',
    'The supplied topic names vitamins A, B-complex, C, D, E, and K, and minerals such as calcium, iron, potassium, iodine, and sodium. Variety helps provide different nutrients. Illness or supplement questions need an adult and health professional.',
    'Curd can contribute calcium, while beans and leafy vegetables can contribute iron.',
    'normal vision skin gums immune infection infections tissues calcium bones teeth iron blood formation potassium iodine sodium small amounts'),
  lesson('food-fibre-water', 'food', 'Why do roughage and water matter?',
    ['Why do roughage and water matter?', 'Is dietary fibre the same as clothing fibre?', 'Does everyone have exactly three quarters body water?', 'How does fibre help digestion?'],
    ['roughage', 'dietary fibre', 'water', 'body water', 'fibre'],
    'Dietary fibre, or roughage, is not digested like starch in the small intestine and supports normal bowel movements. Clothing fibre makes yarn or fabric and is a different meaning. Water is needed for body functions and is present in many foods. The exact body-water percentage varies; there is no one fraction true for everybody.',
    'Food fibre helps normal bowel movements. Cloth fibre makes fabric. The body needs safe water too.',
    'Whole grains, fruit, and vegetables contribute fibre. Cellulose is one plant material that contributes to roughage. Neither fibre nor one food replaces a balanced diet or safe water.',
    'An apple contributes dietary fibre; cotton fibres in a shirt are not food roughage.',
    'food clothing cloth fabric yarn stomach intestine small starch digestion digest percentage fraction bowel movement waste plant cellulose fruit vegetables whole grains',
    ['digestion', 'clothes']),
  lesson('food-balanced', 'food', 'What makes a diet balanced?',
    ['What makes a diet balanced?', 'Is one large meal a balanced diet?', 'Does everybody need the same foods and amounts?', 'What is the difference between diet and meal?'],
    ['balanced diet', 'diet', 'meal', 'food', 'amounts'],
    'A balanced diet supplies varied nutrients in suitable amounts, dietary fibre, and safe water. A diet is the usual food pattern; a meal is one occasion. Needs and suitable choices vary, so one large meal or one identical plan for everybody is not the meaning of balance.',
    'Balance means suitable variety and amounts over a usual food pattern.',
    'Growing and active bodies can have different needs. Food choices may also depend on family preferences or allergies. An adult or qualified professional can help with individual needs; Buddy does not diagnose or prescribe a diet.',
    'Rice or roti, dal, vegetables, and safe water illustrate different contributions without being a fixed prescription for everyone.',
    'variety varied suitable nutrients fibre water usual pattern growth activity individual large same everybody balance amounts'),
  lesson('food-preservation', 'food', 'Why preserve food?',
    ['Why preserve food?', 'Can preservation make spoiled food fresh again?', 'Are all microbes in food harmful?', 'Should I taste suspicious food to check it?'],
    ['preservation', 'preserve', 'spoilage', 'food', 'microbes'],
    'Preservation helps slow changes that make food unsuitable to eat. Drying, pickling, cooling, freezing, and controlled canning or bottling are examples. Preservation does not turn spoiled food fresh again. Some microbes are useful in foods such as curd, but suspicious or mouldy food should not be tasted. Ask an adult.',
    'Preservation slows spoilage. It does not reverse it. Never taste suspicious food to test safety.',
    'Storage needs depend on the food and process. Cold storage or sealing is not a guarantee that all germs are gone. Adults should handle preparation, labels, and safety decisions.',
    'An adult follows the storage label for food rather than assuming anything in a fridge is safe forever.',
    'fresh spoiled spoilt suspicious taste safe safety mouldy germs useful curd label storage slow changes',
    ['digestion']),
  lesson('food-storage-methods', 'food', 'How do preservation methods differ?',
    ['How do food preservation methods differ?', 'What is the difference between refrigeration and deep freezing?', 'Does closing any bottle safely preserve food?', 'Why can drying help preserve food?'],
    ['drying', 'pickling', 'refrigeration', 'deep freezing', 'canning', 'bottling', 'food'],
    'Drying reduces water. Pickling uses suitable preserving conditions. Refrigeration cools food; deep freezing keeps it frozen at a lower temperature. Canning and bottling require controlled processing and sealing. None is simply a promise that every germ is killed, and closing any jar is not enough. Adults handle these processes.',
    'Less water, suitable preserving conditions, cooling, freezing, or controlled sealing are different ideas.',
    'Oil alone or a lid alone does not make food safe. Safe methods depend on the food, clean handling, and proper processes. This guide gives explanations, not cooking, pickling, or home-canning steps.',
    'Raisins show drying; a properly processed bottle of sauce is a different preservation example.',
    'water reduce moisture cool cold lower temperature fridge frozen seal sealing bottles jar cans germs adult processes methods'),
  lesson('food-healthy-routines', 'food', 'How do rest, posture, and activity help?',
    ['How do rest posture and exercise support health?', 'How much sleep do school age children usually need?', 'What are yoga and International Yoga Day?', 'Is posture just sitting stiffly without moving?'],
    ['rest', 'sleep', 'posture', 'exercise', 'yoga'],
    'Rest gives the body a break, and school-age children usually need about 9–12 hours of regular sleep in 24 hours. Posture is body position; comfortable support and changes of position matter, not sitting rigidly forever. Suitable play or supervised yoga can support health. International Yoga Day is on 21 June. Tell an adult about pain or health worries.',
    'Rest, comfortable posture, and suitable movement work with a balanced diet.',
    'A useful routine depends on the person. Children should not choose strenuous exercises or difficult yoga poses alone. This is general revision information, not a diagnosis or personal training plan.',
    'A regular sleep routine, safe play, and a comfortable supported study position are useful habits.',
    'sleep hours school children rest break position body supported comfortable activity play regular stiff rigid June day yoga health'),
  lesson('food-measurements', 'food', 'Kilograms or litres?',
    ['How do grams kilograms litres and kilolitres differ?', 'Does milk have mass as well as volume?', 'What units can food labels use?', 'Is mass the same as volume?'],
    ['gram', 'kilogram', 'litre', 'kilolitre', 'mass', 'volume', 'milk', 'food label'],
    'Grams and kilograms measure mass. Litres and kilolitres measure volume. One kilogram is 1000 grams; one kilolitre is 1000 litres. A liquid such as milk has mass as well as volume. A label choosing litres does not mean liquids cannot have mass.',
    'Mass uses grams or kilograms. Volume uses litres or kilolitres.',
    'Mass describes the amount of matter; volume is space occupied. They are different properties. A food label may choose the unit most useful for that product.',
    'A rice pack may list kilograms, and a milk carton may list litres.',
    'units unit label labels measurement measure grams kilograms litres liters kilolitres kiloliters amount matter space liquid liquids'),
];

export const foodComparisons = [
  { groups: [['carbohydrate'], ['protein', 'fat']], lessonId: 'food-proteins-fats' },
  { groups: [['protein'], ['fat']], lessonId: 'food-proteins-fats' },
  { groups: [['vitamin'], ['mineral']], lessonId: 'food-vitamins-minerals' },
  { groups: [['dietary fibre'], ['clothing fibre']], lessonId: 'food-fibre-water' },
  { groups: [['diet'], ['meal']], lessonId: 'food-balanced' },
  { groups: [['refrigeration'], ['deep freezing']], lessonId: 'food-storage-methods' },
  { groups: [['drying'], ['pickling']], lessonId: 'food-storage-methods' },
  { groups: [['canning'], ['bottling']], lessonId: 'food-storage-methods' },
  { groups: [['mass'], ['volume']], lessonId: 'food-measurements' },
  { groups: [['gram', 'kilogram'], ['litre', 'kilolitre']], lessonId: 'food-measurements' },
];

export const foodTopicLinks = {
  nutrients: ['food'],
  digestion: ['food'],
  microbes: ['food'],
  bacteria: ['food'],
  fungi: ['food'],
  'glucose-starch': ['food'],
  cellulose: ['food'],
  energy: ['food'],
  'matter-mass': ['food'],
  'dietary-fibre': ['digestion', 'animal-adaptations'],
  'food-protein': ['digestion'],
};
